import 'package:flutter/material.dart';

class AppLocalizations {
  final String languageCode;

  AppLocalizations(this.languageCode);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'no_tasks': 'No Tasks Yet',
      'no_tasks_message': 'Start adding tasks to organize your day',
      'add_task_hint': 'Tap the + button to create your first task',
      'app_title': 'ToDo List',
      'edit_task': 'Edit Task',
      'settings': 'Settings',
      'language': 'Language',
      'mode': 'Mode',
      'light': 'Light',
      'dark': 'Dark',
      'done': 'Done!',
      'add_new_task': 'Add New Task',
      'task_added': 'Task added successfully',
      'task_title': 'Task Title',
      'task_details': 'Task Details',
      'select_time': 'Select time',
      'save_changes': 'Save Changes',
      'cancel': 'Cancel',
      'add': 'Add',
      'delete_task': 'Delete Task',
      'delete_confirm': 'Are you sure you want to delete this task?',
      'delete': 'Delete',
      'task_deleted': 'Task deleted',
      'title_hint': 'This is title',
      'details_hint': 'Task details',
      'time': 'Time: ',
      'date': 'Date: ',
      'today': 'Today',
      'mon': 'Mon',
      'tue': 'Tue',
      'wed': 'Wed',
      'thu': 'Thu',
      'fri': 'Fri',
      'sat': 'Sat',
      'sun': 'Sun',
      'january': 'January',
      'february': 'February',
      'march': 'March',
      'april': 'April',
      'may': 'May',
      'june': 'June',
      'july': 'July',
      'august': 'August',
      'september': 'September',
      'october': 'October',
      'november': 'November',
      'december': 'December',
      'logout': 'Logout',
      'logout_confirm': 'Are you sure you want to logout?',
      'logout_success': 'Logout successful',
    },
    'ar': {
      'no_tasks': 'لا توجد مهام بعد',
      'no_tasks_message': 'ابدأ بإضافة المهام لتنظيم يومك',
      'add_task_hint': 'اضغط على زر + لإنشاء مهمتك الأولى',
      'app_title': 'قائمة المهام',
      'edit_task': 'تعديل المهمة',
      'settings': 'الإعدادات',
      'language': 'اللغة',
      'mode': 'الوضع',
      'light': 'فاتح',
      'dark': 'داكن',
      'done': 'تم!',
      'add_new_task': 'إضافة مهمة جديدة',
      'task_added': 'تمت إضافة المهمة بنجاح',
      'task_title': 'عنوان المهمة',
      'task_details': 'تفاصيل المهمة',
      'select_time': 'اختر الوقت',
      'save_changes': 'حفظ التغييرات',
      'cancel': 'إلغاء',
      'add': 'إضافة',
      'delete_task': 'حذف المهمة',
      'delete_confirm': 'هل أنت متأكد من حذف هذه المهمة؟',
      'delete': 'حذف',
      'task_deleted': 'تم حذف المهمة',
      'title_hint': 'هذا هو العنوان',
      'details_hint': 'تفاصيل المهمة',
      'time': 'الوقت: ',
      'date': 'التاريخ: ',
      'today': 'اليوم',
      'mon': 'الإثنين',
      'tue': 'الثلاثاء',
      'wed': 'الأربعاء',
      'thu': 'الخميس',
      'fri': 'الجمعة',
      'sat': 'السبت',
      'sun': 'الأحد',
      'january': 'يناير',
      'february': 'فبراير',
      'march': 'مارس',
      'april': 'أبريل',
      'may': 'مايو',
      'june': 'يونيو',
      'july': 'يوليو',
      'august': 'أغسطس',
      'september': 'سبتمبر',
      'october': 'أكتوبر',
      'november': 'نوفمبر',
      'december': 'ديسمبر',
      'logout': 'تسجيل الخروج',
      'logout_confirm': 'هل أنت متأكد من تسجيل الخروج؟',
      'logout_success': 'تم تسجيل الخروج بنجاح',
    },
    'es': {
      'no_tasks': 'No Hay Tareas',
      'no_tasks_message': 'Comienza a agregar tareas para organizar tu día',
      'add_task_hint': 'Toca el botón + para crear tu primera tarea',
      'app_title': 'Lista de Tareas',
      'edit_task': 'Editar Tarea',
      'settings': 'Configuración',
      'language': 'Idioma',
      'mode': 'Modo',
      'light': 'Claro',
      'dark': 'Oscuro',
      'done': '¡Hecho!',
      'add_new_task': 'Agregar Nueva Tarea',
      'task_added': 'Tarea agregada exitosamente',
      'task_title': 'Título de la Tarea',
      'task_details': 'Detalles de la Tarea',
      'select_time': 'Seleccionar hora',
      'save_changes': 'Guardar Cambios',
      'cancel': 'Cancelar',
      'add': 'Agregar',
      'delete_task': 'Eliminar Tarea',
      'delete_confirm': '¿Estás seguro de que quieres eliminar esta tarea?',
      'delete': 'Eliminar',
      'task_deleted': 'Tarea eliminada',
      'title_hint': 'Este es el título',
      'details_hint': 'Detalles de la tarea',
      'time': 'Hora: ',
      'date': 'Fecha: ',
      'today': 'Hoy',
      'mon': 'Lun',
      'tue': 'Mar',
      'wed': 'Mié',
      'thu': 'Jue',
      'fri': 'Vie',
      'sat': 'Sáb',
      'sun': 'Dom',
      'january': 'Enero',
      'february': 'Febrero',
      'march': 'Marzo',
      'april': 'Abril',
      'may': 'Mayo',
      'june': 'Junio',
      'july': 'Julio',
      'august': 'Agosto',
      'september': 'Septiembre',
      'october': 'Octubre',
      'november': 'Noviembre',
      'december': 'Diciembre',
      'logout': 'Cerrar Sesión',
      'logout_confirm': '¿Estás seguro de que quieres cerrar sesión?',
      'logout_success': 'Cierre de sesión exitoso',
    },
    'fr': {
      'no_tasks': 'Aucune Tâche',
      'no_tasks_message':
          'Commencez à ajouter des tâches pour organiser votre journée',
      'add_task_hint':
          'Appuyez sur le bouton + pour créer votre première tâche',
      'app_title': 'Liste de Tâches',
      'edit_task': 'Modifier la Tâche',
      'settings': 'Paramètres',
      'language': 'Langue',
      'mode': 'Mode',
      'light': 'Clair',
      'dark': 'Sombre',
      'done': 'Fait!',
      'add_new_task': 'Ajouter Nouvelle Tâche',
      'task_added': 'Tâche ajoutée avec succès',
      'task_title': 'Titre de la Tâche',
      'task_details': 'Détails de la Tâche',
      'select_time': 'Sélectionner l\'heure',
      'save_changes': 'Enregistrer les Modifications',
      'cancel': 'Annuler',
      'add': 'Ajouter',
      'delete_task': 'Supprimer la Tâche',
      'delete_confirm': 'Êtes-vous sûr de vouloir supprimer cette tâche?',
      'delete': 'Supprimer',
      'task_deleted': 'Tâche supprimée',
      'title_hint': 'Ceci est le titre',
      'details_hint': 'Détails de la tâche',
      'time': 'Heure: ',
      'date': 'Date: ',
      'today': 'Aujourd\'hui',
      'mon': 'Lun',
      'tue': 'Mar',
      'wed': 'Mer',
      'thu': 'Jeu',
      'fri': 'Ven',
      'sat': 'Sam',
      'sun': 'Dim',
      'january': 'Janvier',
      'february': 'Février',
      'march': 'Mars',
      'april': 'Avril',
      'may': 'Mai',
      'june': 'Juin',
      'july': 'Juillet',
      'august': 'Août',
      'september': 'Septembre',
      'october': 'Octobre',
      'november': 'Novembre',
      'december': 'Décembre',
      'logout': 'Déconnexion',
      'logout_confirm': 'Êtes-vous sûr de vouloir vous déconnecter?',
      'logout_success': 'Déconnexion réussie',
    },
    'de': {
      'no_tasks': 'Keine Aufgaben',
      'no_tasks_message':
          'Fügen Sie Aufgaben hinzu, um Ihren Tag zu organisieren',
      'add_task_hint': 'Tippen Sie auf +, um Ihre erste Aufgabe zu erstellen',
      'app_title': 'Aufgabenliste',
      'edit_task': 'Aufgabe Bearbeiten',
      'settings': 'Einstellungen',
      'language': 'Sprache',
      'mode': 'Modus',
      'light': 'Hell',
      'dark': 'Dunkel',
      'done': 'Erledigt!',
      'add_new_task': 'Neue Aufgabe Hinzufügen',
      'task_added': 'Aufgabe erfolgreich hinzugefügt',
      'task_title': 'Aufgabentitel',
      'task_details': 'Aufgabendetails',
      'select_time': 'Zeit Auswählen',
      'save_changes': 'Änderungen Speichern',
      'cancel': 'Abbrechen',
      'add': 'Hinzufügen',
      'delete_task': 'Aufgabe Löschen',
      'delete_confirm': 'Möchten Sie diese Aufgabe wirklich löschen?',
      'delete': 'Löschen',
      'task_deleted': 'Aufgabe gelöscht',
      'title_hint': 'Dies ist der Titel',
      'details_hint': 'Aufgabendetails',
      'time': 'Zeit: ',
      'date': 'Datum: ',
      'today': 'Heute',
      'mon': 'Mo',
      'tue': 'Di',
      'wed': 'Mi',
      'thu': 'Do',
      'fri': 'Fr',
      'sat': 'Sa',
      'sun': 'So',
      'january': 'Januar',
      'february': 'Februar',
      'march': 'März',
      'april': 'April',
      'may': 'Mai',
      'june': 'Juni',
      'july': 'Juli',
      'august': 'August',
      'september': 'September',
      'october': 'Oktober',
      'november': 'November',
      'december': 'Dezember',
      'logout': 'Abmelden',
      'logout_confirm': 'Möchten Sie sich wirklich abmelden?',
      'logout_success': 'Abmeldung erfolgreich',
    },
    'it': {
      'no_tasks': 'Nessuna Attività',
      'no_tasks_message':
          'Inizia ad aggiungere attività per organizzare la tua giornata',
      'add_task_hint': 'Tocca il pulsante + per creare la tua prima attività',
      'app_title': 'Lista delle Cose da Fare',
      'edit_task': 'Modifica Attività',
      'settings': 'Impostazioni',
      'language': 'Lingua',
      'mode': 'Modalità',
      'light': 'Chiaro',
      'dark': 'Scuro',
      'done': 'Fatto!',
      'add_new_task': 'Aggiungi Nuova Attività',
      'task_added': 'Attività aggiunta con successo',
      'task_title': 'Titolo Attività',
      'task_details': 'Dettagli Attività',
      'select_time': 'Seleziona ora',
      'save_changes': 'Salva Modifiche',
      'cancel': 'Annulla',
      'add': 'Aggiungi',
      'delete_task': 'Elimina Attività',
      'delete_confirm': 'Sei sicuro di voler eliminare questa attività?',
      'delete': 'Elimina',
      'task_deleted': 'Attività eliminata',
      'title_hint': 'Questo è il titolo',
      'details_hint': 'Dettagli attività',
      'time': 'Ora: ',
      'date': 'Data: ',
      'today': 'Oggi',
      'mon': 'Lun',
      'tue': 'Mar',
      'wed': 'Mer',
      'thu': 'Gio',
      'fri': 'Ven',
      'sat': 'Sab',
      'sun': 'Dom',
      'january': 'Gennaio',
      'february': 'Febbraio',
      'march': 'Marzo',
      'april': 'Aprile',
      'may': 'Maggio',
      'june': 'Giugno',
      'july': 'Luglio',
      'august': 'Agosto',
      'september': 'Settembre',
      'october': 'Ottobre',
      'november': 'Novembre',
      'december': 'Dicembre',
      'logout': 'Esci',
      'logout_confirm': 'Sei sicuro di voler uscire?',
      'logout_success': 'Disconnessione riuscita',
    },
    'ru': {
      'no_tasks': 'Нет Задач',
      'no_tasks_message':
          'Начните добавлять задачи, чтобы организовать свой день',
      'add_task_hint': 'Нажмите кнопку +, чтобы создать первую задачу',
      'app_title': 'Список Дел',
      'edit_task': 'Редактировать Задачу',
      'settings': 'Настройки',
      'language': 'Язык',
      'mode': 'Режим',
      'light': 'Светлый',
      'dark': 'Тёмный',
      'done': 'Готово!',
      'add_new_task': 'Добавить Новую Задачу',
      'task_added': 'Задача успешно добавлена',
      'task_title': 'Название Задачи',
      'task_details': 'Детали Задачи',
      'select_time': 'Выберите время',
      'save_changes': 'Сохранить Изменения',
      'cancel': 'Отмена',
      'add': 'Добавить',
      'delete_task': 'Удалить Задачу',
      'delete_confirm': 'Вы уверены, что хотите удалить эту задачу?',
      'delete': 'Удалить',
      'task_deleted': 'Задача удалена',
      'title_hint': 'Это заголовок',
      'details_hint': 'Детали задачи',
      'time': 'Время: ',
      'date': 'Дата: ',
      'today': 'Сегодня',
      'mon': 'Пн',
      'tue': 'Вт',
      'wed': 'Cp',
      'thu': 'Чт',
      'fri': 'Пт',
      'sat': 'C6',
      'sun': 'Bc',
      'january': 'Январь',
      'february': 'Февраль',
      'march': 'Март',
      'april': 'Апрель',
      'may': 'Май',
      'june': 'Июнь',
      'july': 'Июль',
      'august': 'Август',
      'september': 'Сентябрь',
      'october': 'Октябрь',
      'november': 'Ноябрь',
      'december': 'Декабрь',
      'logout': 'Выйти',
      'logout_confirm': 'Вы уверены, что хотите выйти?',
      'logout_success': 'Выход выполнен успешно',
    },
    'tr': {
      'no_tasks': 'Görev Yok',
      'no_tasks_message':
          'Gününüzü organize etmek için görev eklemeye başlayın',
      'add_task_hint': 'İlk görevinizi oluşturmak için + düğmesine dokunun',
      'app_title': 'Yapılacaklar Listesi',
      'edit_task': 'Görevi Düzenle',
      'settings': 'Ayarlar',
      'language': 'Dil',
      'mode': 'Mod',
      'light': 'Açık',
      'dark': 'Koyu',
      'done': 'Tamamlandı!',
      'add_new_task': 'Yeni Görev Ekle',
      'task_added': 'Görev başarıyla eklendi',
      'task_title': 'Görev Başlığı',
      'task_details': 'Görev Detayları',
      'select_time': 'Zaman Seç',
      'save_changes': 'Değişiklikleri Kaydet',
      'cancel': 'İptal',
      'add': 'Ekle',
      'delete_task': 'Görevi Sil',
      'delete_confirm': 'Bu görevi silmek istediğinizden emin misiniz?',
      'delete': 'Sil',
      'task_deleted': 'Görev silindi',
      'title_hint': 'Bu başlık',
      'details_hint': 'Görev detayları',
      'time': 'Zaman: ',
      'date': 'Tarih: ',
      'today': 'Bugün',
      'mon': 'Pzt',
      'tue': 'Sal',
      'wed': 'Çar',
      'thu': 'Per',
      'fri': 'Cum',
      'sat': 'Cmt',
      'sun': 'Paz',
      'january': 'Ocak',
      'february': 'Şubat',
      'march': 'Mart',
      'april': 'Nisan',
      'may': 'Mayıs',
      'june': 'Haziran',
      'july': 'Temmuz',
      'august': 'Ağustos',
      'september': 'Eylül',
      'october': 'Ekim',
      'november': 'Kasım',
      'december': 'Aralık',
      'logout': 'Çıkış Yap',
      'logout_confirm': 'Çıkış yapmak istediğinizden emin misiniz?',
      'logout_success': 'Çıkış başarılı',
    },
    'hi': {
      'no_tasks': 'कोई कार्य नहीं',
      'no_tasks_message':
          'अपने दिन को व्यवस्थित करने के लिए कार्य जोड़ना शुरू करें',
      'add_task_hint': 'अपना पहला कार्य बनाने के लिए + बटन पर टैप करें',
      'app_title': 'कार्य सूची',
      'edit_task': 'कार्य संपादित करें',
      'settings': 'सेटिंग्स',
      'language': 'भाषा',
      'mode': 'मोड',
      'light': 'प्रकाश',
      'dark': 'अंधेरा',
      'done': 'पूर्ण!',
      'add_new_task': 'नया कार्य जोड़ें',
      'task_added': 'कार्य सफलतापूर्वक जोड़ा गया',
      'task_title': 'कार्य शीर्षक',
      'task_details': 'कार्य विवरण',
      'select_time': 'समय चुनें',
      'save_changes': 'परिवर्तन सहेजें',
      'cancel': 'रद्द करें',
      'add': 'जोड़ें',
      'delete_task': 'कार्य हटाएं',
      'delete_confirm': 'क्या आप वाकई इस कार्य को हटाना चाहते हैं?',
      'delete': 'हटाएं',
      'task_deleted': 'कार्य हटा दिया गया',
      'title_hint': 'यह शीर्षक है',
      'details_hint': 'कार्य विवरण',
      'time': 'समय: ',
      'date': 'तारीख: ',
      'today': 'आज',
      'mon': 'सोम',
      'tue': 'मंगल',
      'wed': 'बुध',
      'thu': 'गुरु',
      'fri': 'शुक्र',
      'sat': 'शनि',
      'sun': 'रवि',
      'january': 'जनवरी',
      'february': 'फ़रवरी',
      'march': 'मार्च',
      'april': 'अप्रैल',
      'may': 'मई',
      'june': 'जून',
      'july': 'जुलाई',
      'august': 'अगस्त',
      'september': 'सितंबर',
      'october': 'अक्टूबर',
      'november': 'नवंबर',
      'december': 'दिसंबर',
      'logout': 'लॉगआउट',
      'logout_confirm': 'क्या आप वाकई लॉगआउट करना चाहते हैं?',
      'logout_success': 'लॉगआउट सफल',
    },
    'zh': {
      'no_tasks': '暂无任务',
      'no_tasks_message': '开始添加任务来组织您的一天',
      'add_task_hint': '点击 + 按钮创建您的第一个任务',
      'app_title': '待办事项列表',
      'edit_task': '编辑任务',
      'settings': '设置',
      'language': '语言',
      'mode': '模式',
      'light': '浅色',
      'dark': '深色',
      'done': '完成！',
      'add_new_task': '添加新任务',
      'task_added': '任务添加成功',
      'task_title': '任务标题',
      'task_details': '任务详情',
      'select_time': '选择时间',
      'save_changes': '保存更改',
      'cancel': '取消',
      'add': '添加',
      'delete_task': '删除任务',
      'delete_confirm': '您确定要删除此任务吗？',
      'delete': '删除',
      'task_deleted': '任务已删除',
      'title_hint': '这是标题',
      'details_hint': '任务详情',
      'time': '时间：',
      'date': '日期：',
      'today': '今天',
      'mon': '周一',
      'tue': '周二',
      'wed': '周三',
      'thu': '周四',
      'fri': '周五',
      'sat': '周六',
      'sun': '周日',
      'january': '一月',
      'february': '二月',
      'march': '三月',
      'april': '四月',
      'may': '五月',
      'june': '六月',
      'july': '七月',
      'august': '八月',
      'september': '九月',
      'october': '十月',
      'november': '十一月',
      'december': '十二月',
      'logout': '登出',
      'logout_confirm': '您确定要登出吗？',
      'logout_success': '登出成功',
    },
    'pt': {
      'no_tasks': 'Nenhuma Tarefa',
      'no_tasks_message': 'Comece a adicionar tarefas para organizar seu dia',
      'add_task_hint': 'Toque no botão + para criar sua primeira tarefa',
      'app_title': 'Lista de Tarefas',
      'edit_task': 'Editar Tarefa',
      'settings': 'Configurações',
      'language': 'Idioma',
      'mode': 'Modo',
      'light': 'Claro',
      'dark': 'Escuro',
      'done': 'Concluído!',
      'add_new_task': 'Adicionar Nova Tarefa',
      'task_added': 'Tarefa adicionada com sucesso',
      'task_title': 'Título da Tarefa',
      'task_details': 'Detalhes da Tarefa',
      'select_time': 'Selecionar hora',
      'save_changes': 'Salvar Alterações',
      'cancel': 'Cancelar',
      'add': 'Adicionar',
      'delete_task': 'Excluir Tarefa',
      'delete_confirm': 'Tem certeza de que deseja excluir esta tarefa?',
      'delete': 'Excluir',
      'task_deleted': 'Tarefa excluída',
      'title_hint': 'Este é o título',
      'details_hint': 'Detalhes da tarefa',
      'time': 'Hora: ',
      'date': 'Data: ',
      'today': 'Hoje',
      'mon': 'Seg',
      'tue': 'Ter',
      'wed': 'Qua',
      'thu': 'Qui',
      'fri': 'Sex',
      'sat': 'Sáb',
      'sun': 'Dom',
      'january': 'Janeiro',
      'february': 'Fevereiro',
      'march': 'Março',
      'april': 'Abril',
      'may': 'Maio',
      'june': 'Junho',
      'july': 'Julho',
      'august': 'Agosto',
      'september': 'Setembro',
      'october': 'Outubro',
      'november': 'Novembro',
      'december': 'Dezembro',
      'logout': 'Sair',
      'logout_confirm': 'Tem certeza de que deseja sair?',
      'logout_success': 'Logout bem-sucedido',
    },
    'nl': {
      'no_tasks': 'Geen Taken',
      'no_tasks_message':
          'Begin met het toevoegen van taken om je dag te organiseren',
      'add_task_hint': 'Tik op de + knop om je eerste taak te maken',
      'app_title': 'Takenlijst',
      'edit_task': 'Taak Bewerken',
      'settings': 'Instellingen',
      'language': 'Taal',
      'mode': 'Modus',
      'light': 'Licht',
      'dark': 'Donker',
      'done': 'Klaar!',
      'add_new_task': 'Nieuwe Taak Toevoegen',
      'task_added': 'Taak succesvol toegevoegd',
      'task_title': 'Taaktitel',
      'task_details': 'Taakdetails',
      'select_time': 'Selecteer tijd',
      'save_changes': 'Wijzigingen Opslaan',
      'cancel': 'Annuleren',
      'add': 'Toevoegen',
      'delete_task': 'Taak Verwijderen',
      'delete_confirm': 'Weet je zeker dat je deze taak wilt verwijderen?',
      'delete': 'Verwijderen',
      'task_deleted': 'Taak verwijderd',
      'title_hint': 'Dit is de titel',
      'details_hint': 'Taakdetails',
      'time': 'Tijd: ',
      'date': 'Datum: ',
      'today': 'Vandaag',
      'mon': 'Ma',
      'tue': 'Di',
      'wed': 'Wo',
      'thu': 'Do',
      'fri': 'Vr',
      'sat': 'Za',
      'sun': 'Zo',
      'january': 'Januari',
      'february': 'Februari',
      'march': 'Maart',
      'april': 'April',
      'may': 'Mei',
      'june': 'Juni',
      'july': 'Juli',
      'august': 'Augustus',
      'september': 'September',
      'october': 'Oktober',
      'november': 'November',
      'december': 'December',
      'logout': 'Uitloggen',
      'logout_confirm': 'Weet je zeker dat je wilt uitloggen?',
      'logout_success': 'Uitloggen geslaagd',
    },
    'ko': {
      'no_tasks': '할 일 없음',
      'no_tasks_message': '하루를 정리하려면 작업 추가를 시작하세요',
      'add_task_hint': '+ 버튼을 탭하여 첫 번째 작업을 만드세요',
      'app_title': '할 일 목록',
      'edit_task': '작업 편집',
      'settings': '설정',
      'language': '언어',
      'mode': '모드',
      'light': '밝게',
      'dark': '어둡게',
      'done': '완료!',
      'add_new_task': '새 작업 추가',
      'task_added': '작업이 성공적으로 추가되었습니다',
      'task_title': '작업 제목',
      'task_details': '작업 세부정보',
      'select_time': '시간 선택',
      'save_changes': '변경사항 저장',
      'cancel': '취소',
      'add': '추가',
      'delete_task': '작업 삭제',
      'delete_confirm': '이 작업을 삭제하시겠습니까?',
      'delete': '삭제',
      'task_deleted': '작업이 삭제되었습니다',
      'title_hint': '제목입니다',
      'details_hint': '작업 세부정보',
      'time': '시간: ',
      'date': '날짜: ',
      'today': '오늘',
      'mon': '월',
      'tue': '화',
      'wed': '수',
      'thu': '목',
      'fri': '금',
      'sat': '토',
      'sun': '일',
      'january': '1월',
      'february': '2월',
      'march': '3월',
      'april': '4월',
      'may': '5월',
      'june': '6월',
      'july': '7월',
      'august': '8월',
      'september': '9월',
      'october': '10월',
      'november': '11월',
      'december': '12월',
      'logout': '로그아웃',
      'logout_confirm': '로그아웃하시겠습니까?',
      'logout_success': '로그아웃 성공',
    },
  };

  String get noTasks => _localizedValues[languageCode]!['no_tasks']!;
  String get noTasksMessage =>
      _localizedValues[languageCode]!['no_tasks_message']!;
  String get addTaskHint => _localizedValues[languageCode]!['add_task_hint']!;
  String get appTitle => _localizedValues[languageCode]!['app_title']!;
  String get editTask => _localizedValues[languageCode]!['edit_task']!;
  String get settings => _localizedValues[languageCode]!['settings']!;
  String get language => _localizedValues[languageCode]!['language']!;
  String get mode => _localizedValues[languageCode]!['mode']!;
  String get light => _localizedValues[languageCode]!['light']!;
  String get dark => _localizedValues[languageCode]!['dark']!;
  String get done => _localizedValues[languageCode]!['done']!;
  String get addNewTask => _localizedValues[languageCode]!['add_new_task']!;
  String get taskAdded => _localizedValues[languageCode]!['task_added']!;
  String get taskTitle => _localizedValues[languageCode]!['task_title']!;
  String get taskDetails => _localizedValues[languageCode]!['task_details']!;
  String get selectTime => _localizedValues[languageCode]!['select_time']!;
  String get saveChanges => _localizedValues[languageCode]!['save_changes']!;
  String get cancel => _localizedValues[languageCode]!['cancel']!;
  String get add => _localizedValues[languageCode]!['add']!;
  String get deleteTask => _localizedValues[languageCode]!['delete_task']!;
  String get deleteConfirm =>
      _localizedValues[languageCode]!['delete_confirm']!;
  String get delete => _localizedValues[languageCode]!['delete']!;
  String get taskDeleted => _localizedValues[languageCode]!['task_deleted']!;
  String get titleHint => _localizedValues[languageCode]!['title_hint']!;
  String get detailsHint => _localizedValues[languageCode]!['details_hint']!;
  String get time => _localizedValues[languageCode]!['time']!;
  String get date => _localizedValues[languageCode]!['date']!;
  String get today => _localizedValues[languageCode]!['today']!;
  String get mon => _localizedValues[languageCode]!['mon']!;
  String get tue => _localizedValues[languageCode]!['tue']!;
  String get wed => _localizedValues[languageCode]!['wed']!;
  String get thu => _localizedValues[languageCode]!['thu']!;
  String get fri => _localizedValues[languageCode]!['fri']!;
  String get sat => _localizedValues[languageCode]!['sat']!;
  String get sun => _localizedValues[languageCode]!['sun']!;
  String get january => _localizedValues[languageCode]!['january']!;
  String get february => _localizedValues[languageCode]!['february']!;
  String get march => _localizedValues[languageCode]!['march']!;
  String get april => _localizedValues[languageCode]!['april']!;
  String get may => _localizedValues[languageCode]!['may']!;
  String get june => _localizedValues[languageCode]!['june']!;
  String get july => _localizedValues[languageCode]!['july']!;
  String get august => _localizedValues[languageCode]!['august']!;
  String get september => _localizedValues[languageCode]!['september']!;
  String get october => _localizedValues[languageCode]!['october']!;
  String get november => _localizedValues[languageCode]!['november']!;
  String get december => _localizedValues[languageCode]!['december']!;
  String get logout => _localizedValues[languageCode]!['logout']!;
  String get logoutConfirm =>
      _localizedValues[languageCode]!['logout_confirm']!;
  String get logoutSuccess =>
      _localizedValues[languageCode]!['logout_success']!;

  List<String> getMonths() {
    return [
      january,
      february,
      march,
      april,
      may,
      june,
      july,
      august,
      september,
      october,
      november,
      december,
    ];
  }
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => [
    'en',
    'ar',
    'es',
    'fr',
    'de',
    'it',
    'ru',
    'tr',
    'hi',
    'zh',
    'pt',
    'nl',
    'ko',
  ].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale.languageCode);
  }

  @override
  bool shouldReload(AppLocalizationsDelegate old) => false;
}
