import 'package:flutter/material.dart';

class AppLocalizations {
  final String languageCode;

  AppLocalizations(this.languageCode);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app_title': 'ToDo List',
      'edit_task': 'Edit Task',
      'settings': 'Settings',
      'language': 'Language',
      'mode': 'Mode',
      'light': 'Light',
      'dark': 'Dark',
      'done': 'Done!',
      'add_new_task': 'Add New Task',
      'task_title': 'Task Title',
      'task_details': 'Task Details',
      'select_time': 'Select time',
      'save_changes': 'Save Changes',
      'cancel': 'Cancel',
      'add': 'Add',
      'delete_task': 'Delete Task',
      'delete_confirm': 'Are you sure you want to delete this task?',
      'delete': 'Delete',
      'task_deleted': 'Task deleted',
      'title_hint': 'This is title',
      'details_hint': 'Task details',
      'time': 'Time: ',
      'date': 'Date: ',
      'mon': 'Mon',
      'tue': 'Tue',
      'wed': 'Wed',
      'thu': 'Thu',
      'fri': 'Fri',
      'sat': 'Sat',
      'sun': 'Sun',
    },
    'ar': {
      'app_title': 'قائمة المهام',
      'edit_task': 'تعديل المهمة',
      'settings': 'الإعدادات',
      'language': 'اللغة',
      'mode': 'الوضع',
      'light': 'فاتح',
      'dark': 'داكن',
      'done': 'تم!',
      'add_new_task': 'إضافة مهمة جديدة',
      'task_title': 'عنوان المهمة',
      'task_details': 'تفاصيل المهمة',
      'select_time': 'اختر الوقت',
      'save_changes': 'حفظ التغييرات',
      'cancel': 'إلغاء',
      'add': 'إضافة',
      'delete_task': 'حذف المهمة',
      'delete_confirm': 'هل أنت متأكد من حذف هذه المهمة؟',
      'delete': 'حذف',
      'task_deleted': 'تم حذف المهمة',
      'title_hint': 'هذا هو العنوان',
      'details_hint': 'تفاصيل المهمة',
      'time': 'الوقت: ',
      'date': 'التاريخ: ',
      'mon': 'الإثنين',
      'tue': 'الثلاثاء',
      'wed': 'الأربعاء',
      'thu': 'الخميس',
      'fri': 'الجمعة',
      'sat': 'السبت',
      'sun': 'الأحد',
    },
    'es': {
      'app_title': 'Lista de Tareas',
      'edit_task': 'Editar Tarea',
      'settings': 'Configuración',
      'language': 'Idioma',
      'mode': 'Modo',
      'light': 'Claro',
      'dark': 'Oscuro',
      'done': '¡Hecho!',
      'add_new_task': 'Agregar Nueva Tarea',
      'task_title': 'Título de la Tarea',
      'task_details': 'Detalles de la Tarea',
      'select_time': 'Seleccionar hora',
      'save_changes': 'Guardar Cambios',
      'cancel': 'Cancelar',
      'add': 'Agregar',
      'delete_task': 'Eliminar Tarea',
      'delete_confirm': '¿Estás seguro de que quieres eliminar esta tarea?',
      'delete': 'Eliminar',
      'task_deleted': 'Tarea eliminada',
      'title_hint': 'Este es el título',
      'details_hint': 'Detalles de la tarea',
      'time': 'Hora: ',
      'date': 'Fecha: ',
      'mon': 'Lun',
      'tue': 'Mar',
      'wed': 'Mié',
      'thu': 'Jue',
      'fri': 'Vie',
      'sat': 'Sáb',
      'sun': 'Dom',
    },
    'fr': {
      'app_title': 'Liste de Tâches',
      'edit_task': 'Modifier la Tâche',
      'settings': 'Paramètres',
      'language': 'Langue',
      'mode': 'Mode',
      'light': 'Clair',
      'dark': 'Sombre',
      'done': 'Fait!',
      'add_new_task': 'Ajouter Nouvelle Tâche',
      'task_title': 'Titre de la Tâche',
      'task_details': 'Détails de la Tâche',
      'select_time': 'Sélectionner l\'heure',
      'save_changes': 'Enregistrer les Modifications',
      'cancel': 'Annuler',
      'add': 'Ajouter',
      'delete_task': 'Supprimer la Tâche',
      'delete_confirm': 'Êtes-vous sûr de vouloir supprimer cette tâche?',
      'delete': 'Supprimer',
      'task_deleted': 'Tâche supprimée',
      'title_hint': 'Ceci est le titre',
      'details_hint': 'Détails de la tâche',
      'time': 'Heure: ',
      'date': 'Date: ',
      'mon': 'Lun',
      'tue': 'Mar',
      'wed': 'Mer',
      'thu': 'Jeu',
      'fri': 'Ven',
      'sat': 'Sam',
      'sun': 'Dim',
    },
    'de': {
      'app_title': 'Aufgabenliste',
      'edit_task': 'Aufgabe Bearbeiten',
      'settings': 'Einstellungen',
      'language': 'Sprache',
      'mode': 'Modus',
      'light': 'Hell',
      'dark': 'Dunkel',
      'done': 'Erledigt!',
      'add_new_task': 'Neue Aufgabe Hinzufügen',
      'task_title': 'Aufgabentitel',
      'task_details': 'Aufgabendetails',
      'select_time': 'Zeit Auswählen',
      'save_changes': 'Änderungen Speichern',
      'cancel': 'Abbrechen',
      'add': 'Hinzufügen',
      'delete_task': 'Aufgabe Löschen',
      'delete_confirm': 'Möchten Sie diese Aufgabe wirklich löschen?',
      'delete': 'Löschen',
      'task_deleted': 'Aufgabe gelöscht',
      'title_hint': 'Dies ist der Titel',
      'details_hint': 'Aufgabendetails',
      'time': 'Zeit: ',
      'date': 'Datum: ',
      'mon': 'Mo',
      'tue': 'Di',
      'wed': 'Mi',
      'thu': 'Do',
      'fri': 'Fr',
      'sat': 'Sa',
      'sun': 'So',
    },
    'it': {
      'app_title': 'Lista delle Cose da Fare',
      'edit_task': 'Modifica Attività',
      'settings': 'Impostazioni',
      'language': 'Lingua',
      'mode': 'Modalità',
      'light': 'Chiaro',
      'dark': 'Scuro',
      'done': 'Fatto!',
      'add_new_task': 'Aggiungi Nuova Attività',
      'task_title': 'Titolo Attività',
      'task_details': 'Dettagli Attività',
      'select_time': 'Seleziona ora',
      'save_changes': 'Salva Modifiche',
      'cancel': 'Annulla',
      'add': 'Aggiungi',
      'delete_task': 'Elimina Attività',
      'delete_confirm': 'Sei sicuro di voler eliminare questa attività?',
      'delete': 'Elimina',
      'task_deleted': 'Attività eliminata',
      'title_hint': 'Questo è il titolo',
      'details_hint': 'Dettagli attività',
      'time': 'Ora: ',
      'date': 'Data: ',
      'mon': 'Lun',
      'tue': 'Mar',
      'wed': 'Mer',
      'thu': 'Gio',
      'fri': 'Ven',
      'sat': 'Sab',
      'sun': 'Dom',
    },
    'ru': {
      'app_title': 'Список Дел',
      'edit_task': 'Редактировать Задачу',
      'settings': 'Настройки',
      'language': 'Язык',
      'mode': 'Режим',
      'light': 'Светлый',
      'dark': 'Тёмный',
      'done': 'Готово!',
      'add_new_task': 'Добавить Новую Задачу',
      'task_title': 'Название Задачи',
      'task_details': 'Детали Задачи',
      'select_time': 'Выберите время',
      'save_changes': 'Сохранить Изменения',
      'cancel': 'Отмена',
      'add': 'Добавить',
      'delete_task': 'Удалить Задачу',
      'delete_confirm': 'Вы уверены, что хотите удалить эту задачу?',
      'delete': 'Удалить',
      'task_deleted': 'Задача удалена',
      'title_hint': 'Это заголовок',
      'details_hint': 'Детали задачи',
      'time': 'Время: ',
      'date': 'Дата: ',
      'mon': 'Пн',
      'tue': 'Вт',
      'wed': 'Ср',
      'thu': 'Чт',
      'fri': 'Пт',
      'sat': 'Сб',
      'sun': 'Вс',
    },
    'tr': {
      'app_title': 'Yapılacaklar Listesi',
      'edit_task': 'Görevi Düzenle',
      'settings': 'Ayarlar',
      'language': 'Dil',
      'mode': 'Mod',
      'light': 'Açık',
      'dark': 'Koyu',
      'done': 'Tamamlandı!',
      'add_new_task': 'Yeni Görev Ekle',
      'task_title': 'Görev Başlığı',
      'task_details': 'Görev Detayları',
      'select_time': 'Zaman Seç',
      'save_changes': 'Değişiklikleri Kaydet',
      'cancel': 'İptal',
      'add': 'Ekle',
      'delete_task': 'Görevi Sil',
      'delete_confirm': 'Bu görevi silmek istediğinizden emin misiniz?',
      'delete': 'Sil',
      'task_deleted': 'Görev silindi',
      'title_hint': 'Bu başlık',
      'details_hint': 'Görev detayları',
      'time': 'Zaman: ',
      'date': 'Tarih: ',
      'mon': 'Pzt',
      'tue': 'Sal',
      'wed': 'Çar',
      'thu': 'Per',
      'fri': 'Cum',
      'sat': 'Cmt',
      'sun': 'Paz',
    },
    'hi': {
      'app_title': 'कार्य सूची',
      'edit_task': 'कार्य संपादित करें',
      'settings': 'सेटिंग्स',
      'language': 'भाषा',
      'mode': 'मोड',
      'light': 'प्रकाश',
      'dark': 'अंधेरा',
      'done': 'पूर्ण!',
      'add_new_task': 'नया कार्य जोड़ें',
      'task_title': 'कार्य शीर्षक',
      'task_details': 'कार्य विवरण',
      'select_time': 'समय चुनें',
      'save_changes': 'परिवर्तन सहेजें',
      'cancel': 'रद्द करें',
      'add': 'जोड़ें',
      'delete_task': 'कार्य हटाएं',
      'delete_confirm': 'क्या आप वाकई इस कार्य को हटाना चाहते हैं?',
      'delete': 'हटाएं',
      'task_deleted': 'कार्य हटा दिया गया',
      'title_hint': 'यह शीर्षक है',
      'details_hint': 'कार्य विवरण',
      'time': 'समय: ',
      'date': 'तारीख: ',
      'mon': 'सोम',
      'tue': 'मंगल',
      'wed': 'बुध',
      'thu': 'गुरु',
      'fri': 'शुक्र',
      'sat': 'शनि',
      'sun': 'रवि',
    },
    'zh': {
      'app_title': '待办事项列表',
      'edit_task': '编辑任务',
      'settings': '设置',
      'language': '语言',
      'mode': '模式',
      'light': '浅色',
      'dark': '深色',
      'done': '完成！',
      'add_new_task': '添加新任务',
      'task_title': '任务标题',
      'task_details': '任务详情',
      'select_time': '选择时间',
      'save_changes': '保存更改',
      'cancel': '取消',
      'add': '添加',
      'delete_task': '删除任务',
      'delete_confirm': '您确定要删除此任务吗？',
      'delete': '删除',
      'task_deleted': '任务已删除',
      'title_hint': '这是标题',
      'details_hint': '任务详情',
      'time': '时间：',
      'date': '日期：',
      'mon': '周一',
      'tue': '周二',
      'wed': '周三',
      'thu': '周四',
      'fri': '周五',
      'sat': '周六',
      'sun': '周日',
    },
  };

  String get appTitle => _localizedValues[languageCode]!['app_title']!;
  String get editTask => _localizedValues[languageCode]!['edit_task']!;
  String get settings => _localizedValues[languageCode]!['settings']!;
  String get language => _localizedValues[languageCode]!['language']!;
  String get mode => _localizedValues[languageCode]!['mode']!;
  String get light => _localizedValues[languageCode]!['light']!;
  String get dark => _localizedValues[languageCode]!['dark']!;
  String get done => _localizedValues[languageCode]!['done']!;
  String get addNewTask => _localizedValues[languageCode]!['add_new_task']!;
  String get taskTitle => _localizedValues[languageCode]!['task_title']!;
  String get taskDetails => _localizedValues[languageCode]!['task_details']!;
  String get selectTime => _localizedValues[languageCode]!['select_time']!;
  String get saveChanges => _localizedValues[languageCode]!['save_changes']!;
  String get cancel => _localizedValues[languageCode]!['cancel']!;
  String get add => _localizedValues[languageCode]!['add']!;
  String get deleteTask => _localizedValues[languageCode]!['delete_task']!;
  String get deleteConfirm =>
      _localizedValues[languageCode]!['delete_confirm']!;
  String get delete => _localizedValues[languageCode]!['delete']!;
  String get taskDeleted => _localizedValues[languageCode]!['task_deleted']!;
  String get titleHint => _localizedValues[languageCode]!['title_hint']!;
  String get detailsHint => _localizedValues[languageCode]!['details_hint']!;
  String get time => _localizedValues[languageCode]!['time']!;
  String get date => _localizedValues[languageCode]!['date']!;
  String get mon => _localizedValues[languageCode]!['mon']!;
  String get tue => _localizedValues[languageCode]!['tue']!;
  String get wed => _localizedValues[languageCode]!['wed']!;
  String get thu => _localizedValues[languageCode]!['thu']!;
  String get fri => _localizedValues[languageCode]!['fri']!;
  String get sat => _localizedValues[languageCode]!['sat']!;
  String get sun => _localizedValues[languageCode]!['sun']!;
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) =>
      ['en', 'ar', 'es', 'fr', 'de', 'it', 'ru', 'tr', 'hi', 'zh'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale.languageCode);
  }

  @override
  bool shouldReload(AppLocalizationsDelegate old) => false;
}
